### ISSUE TITLE
Installation script for arch based systems

### ISSUE THREAD

**Issue by NotMugil** [NotMugil/dotfiles#19]

**Comment by MNkoder** [comment]
hey sorry for asking in this issue, but just wanted to ask if you've completely stopped using the niri desktop?

**Comment by NotMugil** [comment]
@MNkoder No problem. I did try Niri on my secondary system for a while, but I haven't had the chance to use it as much as my primary system. I'll check it out again soon when I have a chance and see how things are in that side.

**Comment by MNkoder** [comment]
> @MNkoder No problem. I did try Niri on my secondary system for a while, but I haven't had the chance to use it as much as my primary system. I'll check it out again soon when I have a chance and see how things are in that side.

thanks for the response mate, waiting for the installation script to come out so i can finally use one of your beautiful desktops 🙂 i was getting errors when following the instructions
